version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development

  # test:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.test
  #   volumes:
  #     - .:/app
  #   environment:
  #     - PYTHONPATH=/app
  #   command: ["pytest", "app/tests"]
