version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"  # Map port 5000 on the host to port 5000 in the container
    volumes:
      - .:/app  # Mount the current directory on the host to /app in the container
    environment:
      - FLASK_ENV=development  # Set the environment variable FLASK_ENV to development
